# Generated by Django 3.2.25 on 2024-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20241206_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_year',
            field=models.IntegerField(default=0),
        ),
    ]
