# Generated by Django 3.2.25 on 2024-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_data_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(max_length=50),
        ),
    ]
