# Generated by Django 3.2.25 on 2024-12-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20241206_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
