# Generated by Django 3.2.25 on 2024-12-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_data_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pestle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
